[build]
  command = "pnpm install && pnpm run build"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
